import { reactive } from "vue";
export let datas = reactive({
  eqmTypeOptions: [],
  trre1: {
    id: "g1",
    name: "集团",
    leader: "xxxxxx",
    count: 123456,
    label: "538.90",
    currency: "Yuan",
    rate: 1,
    status: "B",
    variableName: "V1",
    variableValue: 0.341,
    variableUp: false,
    children: [
      {
        id: "g12",
        name: "集团人力资源部",
        leader: "xxxxxx",
        count: 123456,
        label: "338.00",
        rate: 0.627,
        status: "R",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.179,
        variableUp: true,
        children: [
          {
            id: "g121",
            name: "集团CoE部",
            leader: "xxxxxx",
            collapsed: true,
            count: 123456,
            label: "138.00",
            rate: 0.123,
            status: "B",
            currency: "Yuan",
            variableName: "V2",
            variableValue: 0.27,
            variableUp: true,
            children: [
              {
                id: "g1211",
                name: "培训课",
                leader: "xxxxxx",
                count: 123456,
                label: "138.00",
                rate: 1,
                status: "B",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.164,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1212",
                name: "组织发展科",
                leader: "xxxxxx",
                count: 123456,
                label: "138.00",
                rate: 1,
                status: "B",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.164,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1213",
                name: "薪酬福利科",
                leader: "xxxxxx",
                count: 123456,
                label: "138.00",
                rate: 1,
                status: "B",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.164,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1214",
                name: "EHRk科",
                leader: "xxxxxx",
                count: 123456,
                label: "138.00",
                rate: 1,
                status: "B",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.164,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1215",
                name: "海外人力资源科",
                leader: "xxxxxx",
                count: 123456,
                label: "138.00",
                rate: 1,
                status: "B",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.164,
                variableUp: false,
                children: [],
                style: {},
              },
            ],
            style: {},
          },
          {
            id: "g122",
            name: "华东人力资源部",
            leader: "xxxxxx",
            collapsed: true,
            count: 123456,
            label: "100.00",
            rate: 0.296,
            status: "G",
            currency: "Yuan",
            variableName: "V1",
            variableValue: 0.259,
            variableUp: true,
            children: [
              {
                id: "g1221",
                name: "华东COO人力资源部",
                leader: "xxxxxx",
                count: 123456,
                label: "40.00",
                rate: 0.4,
                status: "G",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.135,
                variableUp: true,
                children: [
                  {
                    id: "g12211",
                    name: "汽车人力资源组",
                    leader: "xxxxxx",
                    count: 123456,
                    label: "40.00",
                    rate: 1,
                    status: "R",
                    currency: "Yuan",
                    variableName: "V1",
                    variableValue: 0.181,
                    variableUp: true,
                    children: [],
                    style: {},
                  },
                  {
                    id: "g12212",
                    name: "iPadHSG人力资源组",
                    leader: "xxxxxx",
                    count: 123456,
                    label: "40.00",
                    rate: 1,
                    status: "R",
                    currency: "Yuan",
                    variableName: "V1",
                    variableValue: 0.181,
                    variableUp: true,
                    children: [],
                    style: {},
                  },
                ],
                style: {},
              },
              {
                id: "g1222",
                name: "华东模组BG人力资源部",
                leader: "xxxxxx",
                count: 123456,
                label: "60.00",
                rate: 0.6,
                status: "G",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.239,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1223",
                name: "华东猎聘课",
                leader: "xxxxxx",
                count: 123456,
                label: "60.00",
                rate: 0.6,
                status: "G",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.239,
                variableUp: false,
                children: [],
                style: {},
              },
              {
                id: "g1224",
                name: "华东企业文化课",
                leader: "xxxxxx",
                count: 123456,
                label: "60.00",
                rate: 0.6,
                status: "G",
                currency: "Yuan",
                variableName: "V1",
                variableValue: 0.239,
                variableUp: false,
                children: [],
                style: {},
              },
            ],
            style: {},
          },
          {
            id: "g123",
            name: "COO&自动化人力资源部",
            leader: "xxxxxx",
            collapsed: true,
            count: 123456,
            label: "100.00",
            rate: 0.296,
            status: "DI",
            currency: "Yuan",
            variableName: "V2",
            variableValue: 0.131,
            variableUp: false,
            children: [
              // {
              //     "id": "g1231",
              //     "name": "Name8-1",
              //     "count": 123456,
              //     "label": "100.00",
              //     "rate": 1,
              //     "status": "DI",
              //     "currency": "Yuan",
              //     "variableName": "V2",
              //     "variableValue": 0.131,
              //     "variableUp": false,
              //     "children": [],
              //     "style": {}
              // }
            ],
            style: {},
          },
        ],
        style: {},
      },
      // {
      //     "id": "g13",
      //     "name": "Name9",
      //     "count": 123456,
      //     "label": "100.90",
      //     "rate": 0.187,
      //     "status": "B",
      //     "currency": "Yuan",
      //     "variableName": "V2",
      //     "variableValue": 0.221,
      //     "variableUp": true,
      //     "children": [
      //         {
      //             "id": "g131",
      //             "name": "Name10",
      //             "count": 123456,
      //             "label": "33.90",
      //             "rate": 0.336,
      //             "status": "R",
      //             "currency": "Yuan",
      //             "variableName": "V1",
      //             "variableValue": 0.12,
      //             "variableUp": true,
      //             "children": [],
      //             "style": {}
      //         },
      //         {
      //             "id": "g132",
      //             "name": "Name11",
      //             "count": 123456,
      //             "label": "67.00",
      //             "rate": 0.664,
      //             "status": "G",
      //             "currency": "Yuan",
      //             "variableName": "V1",
      //             "variableValue": 0.241,
      //             "variableUp": false,
      //             "children": [],
      //             "style": {}
      //         }
      //     ],
      //     "style": {}
      // },
      {
        id: "g14",
        name: "总裁办公室",
        leader: "xxxxxx",
        count: 123456,
        label: "100.00",
        rate: 0.186,
        status: "G",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.531,
        variableUp: true,
        children: [],
        style: {},
      },
    ],
    style: {},
  },
  aimTreeData: {
    nodes: [
      {
        id: "g1",
        name: "集团",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "538.90",
        currency: "Yuan",
        rate: 1,
        status: "B",
        variableName: "V1",
        variableValue: 0.341,
        variableUp: false,
        style: {},
        children: ["g12", "g14"],
      },
      {
        id: "g12",
        name: "集团人力资源部",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "338.00",
        rate: 0.627,
        status: "R",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.179,
        variableUp: true,
        style: {},
        children: ["g121", "g122", "g123"],
      },
      {
        id: "g121",
        name: "集团CoE部",
        type: "tree-node",
        leader: "xxxxxx",
        collapsed: true,
        count: 123456,
        label: "138.00",
        rate: 0.123,
        status: "B",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.27,
        variableUp: true,
        style: {},
        children: ["g1211", "g1212", "g1213", "g1214", "g1215"],
      },
      {
        id: "g1211",
        name: "培训课",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "138.00",
        rate: 1,
        status: "B",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.164,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1212",
        name: "组织发展科",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "138.00",
        rate: 1,
        status: "B",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.164,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1213",
        name: "薪酬福利科",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "138.00",
        rate: 1,
        status: "B",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.164,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1214",
        name: "EHRk科",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "138.00",
        rate: 1,
        status: "B",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.164,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1215",
        name: "海外人力资源科",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "138.00",
        rate: 1,
        status: "B",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.164,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g122",
        name: "华东人力资源部",
        type: "tree-node",
        leader: "xxxxxx",
        collapsed: true,
        count: 123456,
        label: "100.00",
        rate: 0.296,
        status: "G",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.259,
        variableUp: true,
        style: {},
        children: ["g1221", "g1222", "g1223", "g1224"],
      },
      {
        id: "g1221",
        name: "华东COO人力资源部",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "40.00",
        rate: 0.4,
        status: "G",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.135,
        variableUp: true,
        style: {},
        children: ["g12211", "g12212"],
      },
      {
        id: "g12211",
        name: "汽车人力资源组",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "40.00",
        rate: 1,
        status: "R",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.181,
        variableUp: true,
        style: {},
        children: [],
      },
      {
        id: "g12212",
        name: "iPadHSG人力资源组",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "40.00",
        rate: 1,
        status: "R",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.181,
        variableUp: true,
        style: {},
        children: [],
      },
      {
        id: "g1222",
        name: "华东模组BG人力资源部",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "60.00",
        rate: 0.6,
        status: "G",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.239,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1223",
        name: "华东猎聘课",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "60.00",
        rate: 0.6,
        status: "G",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.239,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g1224",
        name: "华东企业文化课",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "60.00",
        rate: 0.6,
        status: "G",
        currency: "Yuan",
        variableName: "V1",
        variableValue: 0.239,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g123",
        name: "COO&自动化人力资源部",
        type: "tree-node",
        leader: "xxxxxx",
        collapsed: true,
        count: 123456,
        label: "100.00",
        rate: 0.296,
        status: "DI",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.131,
        variableUp: false,
        style: {},
        children: [],
      },
      {
        id: "g14",
        name: "总裁办公室",
        type: "tree-node",
        leader: "xxxxxx",
        count: 123456,
        label: "100.00",
        rate: 0.186,
        status: "G",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.531,
        variableUp: true,
        style: {},
        children: [],
      },
      {
        id: "a1",
        type: "circle",
        name: "a1111111111",
        leader: "xxxxxx",
        count: 123456,
        label: "Circle",
        rate: 0.186,
        status: "G",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.531,
        variableUp: true,
        style: {
          opacity: 0,
          fill: "transparent",
          stroke: "transparent",
        },
        children: [],
        // x: 100,
        // y: 0,
      },
      {
        id: "a2",
        type: "circle",
        name: "a2222222222",
        leader: "xxxxxx",
        count: 123456,
        label: "Circle",
        rate: 0.186,
        status: "G",
        currency: "Yuan",
        variableName: "V2",
        variableValue: 0.531,
        variableUp: true,
        style: {
          // x: 3116,
          // y: 250,
          // opacity: 0,
          // fill: "transparent",
          // stroke: "transparent",
        },
        children: [],
        // x: 250,
        // y: 350,
      },
    ],
    edges: [
      {
        source: "g1",
        target: "g12",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g1",
        target: "g14",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g12",
        target: "g121",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g12",
        target: "g122",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g12",
        target: "g123",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g121",
        target: "g1211",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g121",
        target: "g1212",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g121",
        target: "g1213",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g121",
        target: "g1214",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g121",
        target: "g1215",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g122",
        target: "g1221",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g122",
        target: "g1222",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g122",
        target: "g1223",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g122",
        target: "g1224",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g1221",
        target: "g12211",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "g1221",
        target: "g12212",
        type: "polyline",
        style: {
          router: {
            type: "orth",
          },
          stroke: "#C0C0C0",
        },
      },
      {
        source: "a1",
        target: "a2",
        type: "quadratic",
        // type: "custom-polyline",
        style: {
          // startArrow: true,
          endArrow: true,
          stroke: "#1783FF",
        },
        id: "edge1",
      },
      // {
      //   source: "g122",
      //   target: "g14",
      //   type: "quadratic",
      //   // type: "custom-polyline",
      //   style: {
      //     // startArrow: true,
      //     endArrow: true,
      //     stroke: "#1783FF",
      //   },
      //   id: "edge1",
      // },
      // {
      //   source: "g12",
      //   target: "g122",
      //   type: "quadratic",
      //   // type: "custom-polyline",
      //   style: {
      //     // startArrow: true,
      //     endArrow: true,
      //     stroke: "#1783FF",
      //   },
      //   id: "edge2",
      // },
    ],
  },
});
